version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Test Application
          command: yarn test
          
  deploy:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: Deploy to Webservers
          command: echo "no deploy"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master

