version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Build Application
          command: yarn build
          
  deploy:
    machine:
      image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Build Application
          command: yarn build
      - run:
          name: Deploy to Webservers
          command: scp -r build/* ubuntu@sv.anypayx.com:/opt/anypay.sv/build

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master

